env:
  global:
    - secure: UBarbzs3qQC1//M6u5qYBzaNBKB1MS5/T9Tb9lWoyjXA7fkFFZ0soiT1C6Sj3ywtJcwkFHfSNrKm46ga71BUqCGk34rIcLrYap/Ad9Oz8PorMCndha790ipAd9ydJQ/1zVMJ7KlrLvobPglpp1wEB2CtsW7/5vx1VLUPqbTygBVGc6Gx47VQs0oYHm7tC7FZ5206sXxj3sRodiszdRHW/arV0y0EBzyU1mEj4peNppxFTXQzQ2+z167F9VcXSVnc3CvBVYZld9c6ds/o4PBB86lpFdyRh/wpFmaj371bg8zQOmTOJT7tOmYMIKBnqGyBdTuZ7u3eIQ9+DDw69b765pSDOfHcfFtzJq5KvPzZBEiZQL/+BK74JoTwJrKJSzGhIVFYkvFuOaegnlh/V9xoXgv35MxDJZRGP90er6quSRzjEKVtGGpAX4jIePHeqpHCSwgI7w1zOOE+g29NzrtiZaLvvgTIGfjC27G7YSYwfnIQWbUfEqhZt0jI093G6Ze/aUaBSNKvYjVwF1CwPYqbNctZYM4QznwAh9w6Cc4lbsA1wo4p2twW0YVMSaiiBq17xqM2s4SIz84N80Gmsxxs5ERaRNAU3BfLPbZ8EhcP4LO7Rja3rUgvbnjIvFA7Kpyst3x1sBdwZ26HKJCC/Ps+EmoxkyyWGXtTXtv32SqAEaE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
