env:
  global:
    - secure: xRTI+dNR3FJz9dx/hbdxEBPvn3V5MDUpVSR2u2kX4bxQfjXGxBAu8dmv7tyY2eaJQBqwoOw2o3LuGny+uHyvR2DT7qF1r6VjCn11w/tTVWnPf9v/O5RqyMi9jrUoRpWtMGfnbkW1mkHcSS2g6ulyrhSSj7Q/3XzyzhkzU4bRKY4RS8d+sexpd5uzYD1MsJ3s0k/t+TeXGwo1FGZVe1idvHYrng4UJ9kYxbs4y0Q+PbQe8eYIInk5c5uAlJjbXDYRcco3GKIDYC8QP1MoA8Vn2M4/EQ9BJMM4DMFHAktEnRGDvr6K8CtsWcBTNDZ9nuijFXNuU2Uhht64TiIms34Q54wryzrQwFvtUZfFOkFfxpb7uybEIE7j9E8OAFxvyY9Gx+bjvxOBInIFfUso/QzfQ/iWucWasvvZVODsHWTaFhhOlDXhZT8djg0LBPR/VU33WPjzJLgCsh6CPtmeRMowqLQcsrDUG8NyY5iBOUNygg5utmxaM5U/WHsfjbv9h5quOvOJ1OA2YgBkKTkzTqoFGENutwPtytunAB+hSehd57+xEd+qj5hM6DyQ68LT3XvpWKVnrFhn/upajX/V4//8/rkaw2jOQOaFL+E845PGlEIecaow0oktmpIz/puzFM5OSSoj2C86h0G298u8C27ZflZa/gv2JkwW4YHR4AnRcBA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master
    - UPDATE_ME_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/update_me.py
    - ADMIN_LOCATION: https://raw.githubusercontent.com/dead-hosts/repository-structure/master/admin.py

dist: xenial
sudo: required

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

before_script:
  - if [[ ! -f .administrators ]]; then wget "${UPDATE_ME_LOCATION}" -o /dev/null -O update_me.py && chmod +x update_me.py; else echo "update_me not downloaded :)"; fi
  - if [[ ! -f .administrators ]]; then wget "${ADMIN_LOCATION}" -o /dev/null -O admin.py && chmod +x admin.py; else echo "admin not downloaded :)"; fi

script:
  - python3 update_me.py

notifications:
  on_success: change
  on_failure: always
