env:
  global:
    - secure: OxJESf9yzEEeLpfDO63gsc7Ct1OMxmdT5zMjlS4C8EnRs0SAoaJ3PpO10GsISuZhot3CuQx+WnD6/wDaK/MbcfHZjkzwaEJBTzdL4UPAgrjjadUr2FRSfkV1CtV5yo5LWm8Ccbc8g6p2oTUavKON8mV29zkvknMJS36T5y70NXIPJcD/WNcBHi99TrCgx5Hd7Q7usonC3H75+rfXvgeoMrHuDDThPEx/R+3O/5XV9yUE6+PzZBdP1nmdn2WaDTe7PTO8xor2YFLXfNOcoXC7NTCIbACKYdWaTSF/D+UHrz+12wCwlUhg3tEahrD8rzDmRXrhU2Vg2BUO9VMzjaN2+Kqo51LFmBvvIsuHSKTKkYkMuGoBgexcRf5zp4uZX/1bZmBsHWno0xm0UfSkLQhCHyIYLqcPOxZWckqWWcEwAbN6RaNrOg6ukPvpAVdpsLBk+wxsA/IA5qXp/Cq6vbUmd5/xflGxOooyo3yTzckG/D7Bu3a2t9g5QkiQ0GCS5SDvZJpH+JgaldpQ+3inGwWF8d9+rLKjBIJyiGzbL310R4nIMoV3EsYlxRx/rqJZHJUfje637Yf2Co0rx4B5mGpLF4ivjCi7AUqHIY1rT5dwHAtiI0BFSkYhWfxhgj/ETJJK+xZT5v7aB1cqASDdI2xWS/kfgg4gkDKtG2U9G00DIBE=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
