env:
  global:
    - secure: kLcPRIU8h9rQJHrMFl4+JyZzEOLh53ZHffBwmVYXc7zfvXxHLcpSqepmqfQ1leo/zMb2+S4woyP3oR1cBVHqrAWxAtsk4CDjVn1/URqLbJTP6Zfll1UzhmAOjIdKuoYYy6OhuhoIDFyN+HZxwJ1Xx2BlRNw7IOTvYWwu7BRbkPkqQ0qL6L5DdpPiolFgAo8f77+lFebaFUrdveBb194qYS2LodIIrcNfQcZYyffih6B4WodFx7Wtzb/sbFENX0lp+kxZUDoer+OnNNAed5F9cdELPxGJJZb3hWv0iFBxvHbswtmxvzIjTmbqhmlfA9rba8G1e/6eEKcPLoC3+veZd+M+ZGaKH/bKvUdt17LnmUSDc405PXDnUSRmTnUU8xgGNC1/Ky/9cDUlkWXQNEev0DOdulC7rjNPw/8Z9dv3RXtwM5wtpINxX5Go7sVB/Q5lE6iOgwVz+dI4F7V28ZlQrmoY3kQi7RRCjM32q1MBAJXILBYwO0qJiC0FMFBphVi8mnwSxhdxSGz24FrUeNKabkzm5Yho5Lxcy15PCwn/2+J63TqJnFH/52zPR0ebthpJ3r18pY8wu0ba1eDYHLlp9rjj42QKR/XOOcHshjEV9IH2vr0zSElibCSituyJ32IsdgZ//sPw4XaJNgUdTz0wnr7RgarECySoWw14a0BhW8o=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
