env:
  global:
    - secure: ESTIXWWqenYXLOnm4fU0NaHLsEMsm8vhlGIJGwU8R/IzPWarEphUph9M40NTTFRBFftudvb4k/YIcUswVLtkpf8Vtg0Br0VGKoAGcx0cJE/g8P0C0zVIBvp+Dx8JMHoeHiAHXwfWIRUlzdNccVLOWcAe6qG6/zCPKZvc/lwgSRqQJXzgaSjqwbLenU/S5/acwPj96X5sQfKuq5VlljBo3mNPTXYIgmRIHBhxBclpiCSBqvmiQHpRNVhe5W5fZaznZxtqj52JOPVKaJE6lbQY3WdJGvCbwQmDd+rQc/zt/hQQp3gRVxIZX0qnq4uj/FDo4zany6bn4WQD74u4mRj2+qAUanQOIoiyX8z9D0m3BhlqYTb34A7nMna8nyMa5xHrVf88m1MrgLBwdZvnscNab/GxM/eB1Wlx6ltFtMXWBKmDVkxlvNckTVYts7GidIU4XgJWzX9fEUZDbWa8zKNOdDkzdr6nHU/VeK+H2m1eNjIDSbaiR5yx94JAK1IaDrTC8ajzWplQXshG99K+DHGXwKCjmhe+PhNvqLptgNgiq7uQCCGHDt5VDchTjPA5a2XV9+qz24eTh3lZn5Yw7I6f7ZLyX6uOm8GL4KP/9j1+jbV4GGqWtehPUVQD+ntF/TTWmUbM2JvsM4yBlOHsggE5ASOUNPEAkb/8btQM6E5OK3Q=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
