env:
  global:
    - secure: LCSu/KgTgfSJI6sPB9IuQKwoN1wDtlvKpp+Ylvbofh6E1Z8UfhmNevyTfPkS1YJEaSifu3mHqqiIt5IriQHYHVimiw+ozN0D2fGcj25P8YRULBd4MmHyXEDtJ4DMJzl4a9cluFyVjpJXcDyVDYeJCHh9/T99slUr1Ivk+o2HzzFpagCZz2kU7FQOfRYw+CEqJB/TLpYpamyWe0Yos2MAEIv16x+vMRLlCr9e0j74U20jFDtEagBHJNOCbhvxSFRz61K3/96xIRPS+1lMHJaYL3BcejsLbKcOkouwxVPBHQ9SiVrs/9zvzAjq0AETaqVdboyZSdVVtCC1SoeB+qNhI5Cd8Dwv+Qz2O44UqDGRtvTCSOwT8lau83Ghc/lkoRZUy92ehaukDNBackmO6mzQdOm9B0fxPHbOgdu5JV/ftYls9UX/SXsqAF+U17+NUKiUP0ibF8an5k2RmjMRajBy7b0RxhU3eAaanxIV0hplClYRlDOzJBm3CVyS++rcSqYeSW8jm22wzA9QqWGLRL6fmgBDZVqgjQ2BoglyRrkc5DR/0CxRf4vy4rBXkukltR+3+K36HAL7aXei1W4gxWv9W9d24JClfc6cqR4Ay5TbVPdw+xTUXCVtr8ui3qxIv2usl0f3Yc38Kq4wrWwDqYh4J4k6+hh7vbj1kBq7EoMzOOQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install pyfunceble-dev
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
