env:
  global:
    - secure: TZGhKffYh0qA2R/i9S8srHM1wyVXt73zAl6m2j4Qe+0j5y3Q1nHy+bjhRpuk7D02A6rSgyBa/SIozdE+9QkRn6MN70G9D+gfekkN9ZD2Bh6bYGmr8e3x9pxMqmGq2kY1AWMm2UWbzomS9UcTKU1lRTmEbtPWkBxEx1xaaG2XKUVHdkxnJg/d8E1ZyFiA6dbepUX6t94QxEMEpfglDwwXIj8eiaYg9iIdNkNy1qIaVPt4UccYaDhwi6zmuC/a47W+/Be/v2hd/G5J5THJLkM05W5GwrefziXXW9Ax7hZu5KPrIfgNEQAU2U31hcthNNSzgcaMocQqazQ/9PW8PK7xdVYuELan31XKbXAdOXDo9TbmG4zsXH8yo4S+9kRJgVZsmPVIbVSXMaO/mEq3OYPbkz5eMsraQ/hdpiLwHAAESucK0SC1uTLr5PmPcmLps182MROA0XkrOIKZ0Zyh6ywV5Oh4JQdn8anaHN/CNgyALvO15cCnnw0ticPUzzZKQtZz5F99gWbaoyJFbJ9Vd8yaFsaZgqhXJf7TBU7hcQFuTayiNzwF+SDp8OGo2Ro1OgyoZQ+U4kdQ22UB2c5wFRWLn2QP3//5sqgW7jKpbCCH2Oi/Y/TCdZR4C0+j1YYxolL+SpECi0p+XJtqP5WYVMUVdi52iCmXWRS+SftnGnHgGm8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - pip

sudo: required

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install pyfunceble-dev

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
