env:
  global:
    - secure: FtuDT3OYdfUf50PfKDtjsExalLrm0p6iTOYPAS0oBG8ciGHGlAzU0lkWCC27Sx46aSgSxP/xpDF/h+rdYgR3codbEHkU6XwEFWL+hFyS/vY4vDKuYt2652q13NKceHcMQTGjeRoMqfIc4jiP6e+maPuAwH+LVXtnHPkftC83x206pFKj1Nbe10SyvrOlG2YSXRkk5sKB2CCNFxej6j8/cy7RwRiCtoobT296FlHgMZTbNOfpz47m/Kw/QWR2pdEScipA4s+kkGeTI6Z5B6tCmevgv2vYPJ8+Vixwt7w/pLi5wJmXFP4ooELexydgwU0FBj5WAjrEwio9SWPK2/46FtfNrzhDn8h+8MugGlsiJDQmmawBSVOB3htrJPM46Y33bn6QU7dRYrXRynyfCtq11BiO4N+ZX18BZlwNK8uiklg0BUDbSr6L81SIRCJrs0668zM2C6D2barsKcbwmtl2CkSuxqgkpNIPOEF5ZXGUlIp5leTSBwq2SG91OG6lExPIh7zVfcVv+bg1q4pCPp6dT/+FmHLbWsdyTePCeQ/VRp8i0YLMEDo2/IKNPJwDBl17Q+ZlFxlb0Lw8SIP0haZicla9QUeyLx4u7v/RMUr3Xt19zM48hIRzyL0TYP7CVIhEGzchncmM7Fzu/rlGR8xzcN2PkfvmkJUWqzpIW4501l0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
