env:
  global:
    - secure: kHtRcHsDQNfc+oTxCOHjVDPodDd1/xtCJsfW9x9Au/ldcLOHoHDh7fhOq3faRhMXTqiSl/C7lcV5h1XuiXSrwtCDQY1fBeW4eJm0pe4G0znD7bN44Nnju0ZjoymaDrlovLTQzvIBvSdy0uRNmwuXzbRssutZj22iAhH89wXkWQlDUrNuoMjNHPYSPNyk1vyZ7lhLq6HwFaA9fa01ROjhLbXNycQrnkndCBfWC+ReUH1EtNtUv7cGW8J5xDRNhCR2I1zU9drrafVu3babjQTIfgwPC5ZcuCKCndXWh8wRtVs1IP5g4/2lql0D4H2KFecDgr45SSwxfkyFvjQ+ko0j3DuJsfu83EVgk8+/1yTe6Fe7j1U6sRnfOebd5UFkH442x82watxDkqwOQ+gXBQJBaGhsgvg+n1vPnxEiXBHweURVMYMmiJWV7S1SsOHGELNiTwzEHk1qMgLs7L0YQVeVO8kEUCY+d1Hb0Tx29L8HXJM9y/SHirTLwi6bVysngTsc3uuXOpk3a3JRPyGenQQL5ywXI6NNRhFy3U8Lt7q+rj+Vc9xP0mvPV3FqtRfwQSnL/xsc0YJP3xjT+e68uj01H7PL03vevuZMsVYq8kGeREyHM5+Dk41hfh/2BJSA1Bwf71BO0FOrL515cxHAMLSu/TpNIIk4ZJrscXYpZac3sik=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: dead-hosts/WindowsSpyBlocker-extra_git_crazy-max
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

install:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble
  - sudo apt-get -y install dos2unix

script:
  - python3 ./update_me.py

notifications:
  on_success:   change
  on_failure:   always
